# payment
PAYMENT_TYPE_CK = "1"
PAYMENT_TYPE_TM = "2"
PAYMENT_TYPE_TM_CK = "3"
PAYMENT_TYPE_DTCN = "4"
PAYMENT_TYPE_OTHER = "5"
# payment status
PAYMENT_STATUS_NOT_PAID_YET = "0"
PAYMENT_STATUS_PAID = "1"

# buyer type
BUYER_NOT_NEED_INVOICE = "unidentified"
BUYER_INDIVIDUAL = "individual"
BUYER_COMPANY = "company"

# provider status
PROVIDER_EINVOICE_STATUS_DRAFT = "draft"
PROVIDER_EINVOICE_STATUS_REQUESTED = "creating"
PROVIDER_EINVOICE_STATUS_ISSUED = "created"
PROVIDER_EINVOICE_STATUS_REPLACE = "replace"
PROVIDER_EINVOICE_STATUS_BE_REPLACED = "be_replaced"
PROVIDER_EINVOICE_STATUS_ADJUST = "adjust"
PROVIDER_EINVOICE_STATUS_BE_ADJUSTED = "be_adjusted"
PROVIDER_EINVOICE_STATUS_CANCELED = "canceled"
PROVIDER_EINVOICE_STATUS_UNKNOWN = "unknown"

#
THIS_EINVOICE_BE_REPLACED_BY_OTHER_EINVOICE = 1
THIS_EINVOICE_BE_ADJUSTED_BY_OTHER_EINVOICE = 2

#
INVOICE_LINE_TYPE_PRODUCT = "1"
INVOICE_LINE_TYPE_NOTE = "2"
INVOICE_LINE_TYPE_DISCOUNT = "3"
INVOICE_LINE_TYPE_TABLE_LIST = "4"
INVOICE_LINE_TYPE_OTHER = "5"
